onePasswordSecrets:
  vault: google-analytics-mcp
  manualItem: google-analytics-mcp_production-manual
autoscaling:
  enabled: true
host: mcp-google-analytics.stape.io
image:
  repository: europe-west1-docker.pkg.dev/stape-production/stape/google-analytics-mcp
  tag: 63f66b9-37910075842-1
resources:
  requests:
    cpu: 150m
    memory: 400Mi
