onePasswordSecrets:
  vault: google-analytics-mcp-dev
  manualItem: google-analytics-mcp_dev-manual
host: mcp-google-analytics.stape.dev
image:
  repository: europe-west1-docker.pkg.dev/stape-development/stape/google-analytics-mcp
  tag: 2c1e4f5-37824557158-1
