image:
  repository: "example.com/example"
  name: "app"
  tag: "latest"

host: "example.com"
auth:
  issuerHost: "auth.example.com"

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
