apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "google-analytics-mcp.labels" . | nindent 4 }}
spec:
  commonName: {{ .Values.host | quote }}
  secretName: {{ .Release.Name }}-certificate
  dnsNames:
    - {{ .Values.host | quote }}
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer
