apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "google-analytics-mcp.fullname" . }}
  labels:
    {{- include "google-analytics-mcp.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.host }}`)
      priority: 10
      services:
        - name: {{ include "google-analytics-mcp.fullname" . }}
          namespace: {{ .Release.Namespace }}
          port: 80
  tls:
    secretName: {{ include "google-analytics-mcp.fullname" . }}-certificate
