apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Release.Name }}-manual
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
    operator.1password.io/auto-restart: 'true'
spec:
  itemPath: vaults/{{ .Values.onePasswordSecrets.vault }}/items/{{ .Values.onePasswordSecrets.manualItem }}
