apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "google-analytics-mcp.fullname" . }}
  labels:
    {{- include "google-analytics-mcp.labels" . | nindent 4 }}
automountServiceAccountToken: true
